import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PriceMarquee from "@/components/PriceMarquee";
import Toaster from "@/components/Toaster";

const notoSerifBengali = Noto_Serif_Bengali({
  variable: "--font-noto-serif-bengali",
  subsets: ["bengali","latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="bn" className={`${notoSerifBengali.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Header />
        <PriceMarquee />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
